# workflow name
name: hello world

# triggers
# - indicates a list item
on:
  push:
    branches:
      - main

# - indicates a list item
# | allows for multi line strings, i.e. multiple commands
jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Print date
        run: |
          date
      - name: Print directory long
        run: |
          ls -l